FC_TSFRESH_GAS = {
    "abs_energy": None,
    "approximate_entropy": [{'m': 2, 'r': 0.1},
                            {'m': 2, 'r': 0.3},
                            {'m': 2, 'r': 0.5},
                            {'m': 2, 'r': 0.7},
                            {'m': 2, 'r': 0.9}],
    "autocorrelation": [{'lag': 0},
                        {'lag': 1},
                        {'lag': 2},
                        {'lag': 3},
                        {'lag': 4}],
    "benford_correlation": None,
    "binned_entropy": [{'max_bins': 5}],
    "count_above_mean": None,
    "count_below_mean": None,
    "has_duplicate": None,
    "maximum": None,
    "mean": None,
    "mean_abs_change": None,
    "mean_change": None,
    "mean_second_derivative_central": None,
    "median": None,
    "minimum": None,
    "skewness": None,
    "standard_deviation": None,
    "variance": None,
    "variance_larger_than_standard_deviation": None,
    "variation_coefficient": None,
}
